# Generated by Django 4.0.3 on 2022-10-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_items',
        ),
    ]
